### ISSUE TITLE
Client Design

### ISSUE THREAD

**Issue by chen-robert** [mtday/space-game#1]
I'm confused at the design of Client.java. What is the point of the two private fields? As far as I can see, the Client object isn't passed to anything. Also, assuming there is only one client, maybe make it a static method to allow for easier access without passing around references.

**Comment by chen-robert** [comment]
Upon further reading of the code, it seems that only one Client will ever be created. At least this is what the static design of Display implies.

**Comment by chen-robert** [comment]
#2

**Comment by mtday** [comment]
I updated the client.

Ship should keep the id, eventually that will come from the server.
